version: '3.8'

services:
  php:
    build: .
    container_name: "php"
    image: php:8.1.16-apache
    volumes:
      - ./:/var/www/html/
    ports:
      - "83:80"

  db:
    image: mariadb:10.5
    container_name: "db"
    restart: always
    volumes: 
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
      - mariadb_data:/var/lib/mysql 
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
    ports:
      - "3307:3306"

  node:
    container_name: "node"
    build: ./server
    image: node:14
    volumes:
      - ./server:/app
    working_dir: /app
    command: ["node", "server.js"]
    ports:
      - "3000:3000"
    depends_on:
      - db  # Espera o DB iniciar antes de rodar
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=monitoria  # Nome do seu banco de dados

volumes:
  mariadb_data:
