version: "3.8"

services:
  db:
    image: mariadb:10.5
    container_name: "db"
    restart: always
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
      - mariadb_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
      - TZ=America/Sao_Paulo
    ports:
      - "3307:3306"

  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: "node"
    image: monitoria-node
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=monitoria
    command: ["npm", "start"]
    restart: always

volumes:
  mariadb_data:
